### ISSUE TITLE
Issues with audio streaming

### ISSUE THREAD

**Issue by soywiz** [korlibs/korau#9]

**Comment by TobseF** [comment]
🎶 I tried to play these music files as background-music:
[monkey_drama.mp3](https://github.com/TobseF/Candy-Crush-Clone/blob/AddMsuic/src/commonMain/resources/music/monkey_drama.mp3)
[monkey_island_puzzler.mp3](https://github.com/TobseF/Candy-Crush-Clone/blob/AddMsuic/src/commonMain/resources/music/monkey_island_puzzler.mp3)
> Music by Eric Matyas www.soundimage.org
  

My attempt was to play them with in this way ([JukeBox.kt](https://github.com/TobseF/Candy-Crush-Clone/blob/AddMsuic/src/commonMain/kotlin/j4k/candycrush/JukeBox.kt)):

```kotlin 
newMusic("monkey_island_puzzler.mp3")?.playAndWait()

private suspend fun newMusic(fileName: String) = resourcesVfs["$fileName"].readAudioStream()
```

But the `readAudioStream()` returns `null`. 

Korge `1.5.7.0`.

**Comment by TobseF** [comment]
I thought it's important to use the `readAudioStream()` for bigger files. Now I saw there is also a 
`.readNativeSound(streaming = true)` : 
So I changed the code to: 
``` kotlin
newMusic("monkey_island_puzzler.mp3")?.play()
private suspend fun newMusic(fileName: String) = resourcesVfs["$fileName"]
                                                 .readNativeSound(streaming = true)
```


Now the music plays... but it's too fast.

**Comment by TobseF** [comment]
Anyway we also have to update the 
https://korlibs.soywiz.com/korge/audio/ 
page. And remove the :
> Since this API only support WAV files by default, you have to include separate artifacts to be able to play other formats in the JVM.

> korge {
	dependencyMulti("com.soywiz.korlibs.korau:korau-mp3:$korauVersion") // To be able to play mp3
	dependencyMulti("com.soywiz.korlibs.korau:korau-ogg-vorbis:$korauVersion")
}

**Comment by soywiz** [comment]
Thanks for the info 👍 , that will help me to figure out stuff

**Comment by TobseF** [comment]
In the JS Backend the mp3 is played correctly.

By the way... this is how I will loop the music:

``` kotlin
views.launch {
    while (true) {
        music.play()
        delay(music.length)
    }
}
```

**Comment by TobseF** [comment]
I's also broken on Android
``` java
va.io.IOException: Prepare failed.: status=0x80000000
at android.media.MediaPlayer._prepare(Native Method)
at android.media.MediaPlayer.prepare(MediaPlayer.java:1307)
at com.soywiz.korau.sound.AndroidNativeSound.play(AndroidNativeSoundProvider.kt:59)
at j4k.candycrush.JukeBox.loopMusicPlaylist(JukeBox.kt:35)
at j4k.candycrush.JukeBox$play$1.invokeSuspend(JukeBox.kt:26)
at j4k.candycrush.JukeBox$play$1.invoke(Unknown Source:10)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
at j4k.candycrush.JukeBox.play(JukeBox.kt:25)
at MainKt$main$2.invokeSuspend(main.kt:43)
at MainKt$main$2.invoke(Unknown Source:10)
at com.soywiz.korge.Korge$invoke$2$3.invokeSuspend(Korge.kt:464)
at com.soywiz.korge.Korge$invoke$2$3.invoke(Unknown Source:10)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:9)
at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:461)
at com.soywiz.korge.Korge$invoke$2.invoke(Unknown Source:10)
at com.soywiz.korge.Korge$KoruiWithLogger$2.invokeSuspend(Korge.kt:407)
at com.soywiz.korge.Korge$KoruiWithLogger$2.invoke(Unknown Source:10)
at com.soywiz.korgw.AndroidGameWindow.loop(DefaultGameWindowAndroid.kt:74)
at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:406)
at com.soywiz.korge.Korge.invoke-nom0QHw(Korge.kt:431)
at com.soywiz.korge.Korge.invoke-nom0QHw$default(Korge.kt:429)
at MainKt.main(main.kt:34)
at j4k.candycrush.MainActivity.activityMain(MainActivity.kt:13)
at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invokeSuspend(KorgwActivity.kt:169)
at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at com.soywiz.korgw.KorgwActivity$onCreate$2.invokeSuspend(KorgwActivity.kt:168)
at com.soywiz.korgw.KorgwActivity$onCreate$2.invoke(Unknown Source:10)
at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invokeSuspend(KorioAndroid.kt:8)
at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at com.soywiz.korio.android.KorioAndroidContextKt.withAndroidContext(KorioAndroidContext.kt:19)
at com.soywiz.korio.KorioAndroidKt$Korio$1.invokeSuspend(KorioAndroid.kt:8)
at com.soywiz.korio.KorioAndroidKt$Korio$1.invoke(Unknown Source:10)
at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invokeSuspend(AsyncExtAndroid.kt:7)
at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invoke(Unknown Source:10)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
at com.soywiz.korio.async.AsyncExtAndroidKt.asyncEntryPoint(AsyncExtAndroid.kt:6)
at com.soywiz.korio.KorioAndroidKt.Korio(KorioAndroid.kt:8)
at com.soywiz.korgw.KorgwActivity.onCreate(KorgwActivity.kt:166)
at android.app.Activity.performCreate(Activity.java:7159)
at android.app.Activity.performCreate(Activity.java:7150)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:205)
at android.app.ActivityThread.main(ActivityThread.java:6991)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
	FATAL EXCEPTION: main
	Process: j4k.candycrush, PID: 30951
	java.io.IOException: Prepare failed.: status=0x80000000
		at android.media.MediaPlayer._prepare(Native Method)
		at android.media.MediaPlayer.prepare(MediaPlayer.java:1307)
		at com.soywiz.korau.sound.AndroidNativeSound.play(AndroidNativeSoundProvider.kt:59)
		at j4k.candycrush.JukeBox.loopMusicPlaylist(JukeBox.kt:35)
		at j4k.candycrush.JukeBox$play$1.invokeSuspend(JukeBox.kt:26)
		at j4k.candycrush.JukeBox$play$1.invoke(Unknown Source:10)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
		at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
		at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
		at j4k.candycrush.JukeBox.play(JukeBox.kt:25)
		at MainKt$main$2.invokeSuspend(main.kt:43)
		at MainKt$main$2.invoke(Unknown Source:10)
		at com.soywiz.korge.Korge$invoke$2$3.invokeSuspend(Korge.kt:464)
		at com.soywiz.korge.Korge$invoke$2$3.invoke(Unknown Source:10)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
		at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
		at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:9)
		at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:461)
		at com.soywiz.korge.Korge$invoke$2.invoke(Unknown Source:10)
		at com.soywiz.korge.Korge$KoruiWithLogger$2.invokeSuspend(Korge.kt:407)
		at com.soywiz.korge.Korge$KoruiWithLogger$2.invoke(Unknown Source:10)
		at com.soywiz.korgw.AndroidGameWindow.loop(DefaultGameWindowAndroid.kt:74)
		at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:406)
		at com.soywiz.korge.Korge.invoke-nom0QHw(Korge.kt:431)
		at com.soywiz.korge.Korge.invoke-nom0QHw$default(Korge.kt:429)
		at MainKt.main(main.kt:34)
		at j4k.candycrush.MainActivity.activityMain(MainActivity.kt:13)
		at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invokeSuspend(KorgwActivity.kt:169)
		at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invoke(Unknown Source:10)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
		at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
		at com.soywiz.korgw.KorgwActivity$onCreate$2.invokeSuspend(KorgwActivity.kt:168)
		at com.soywiz.korgw.KorgwActivity$onCreate$2.invoke(Unknown Source:10)
		at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invokeSuspend(KorioAndroid.kt:8)
		at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invoke(Unknown Source:10)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
		at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
		at com.soywiz.korio.android.KorioAndroidContextKt.withAndroidContext(KorioAndroidContext.kt:19)
		at com.soywiz.korio.KorioAndroidKt$Korio$1.invokeSuspend(KorioAndroid.kt:8)
		at com.soywiz.korio.KorioAndroidKt$Korio$1.invoke(Unknown Source:10)
		at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invokeSuspend(AsyncExtAndroid.kt:7)
		at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invoke(Unknown Source:10)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
		at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
		at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
		at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
		at com.soywiz.korio.async.AsyncExtAndroidKt.asyncEntryPoint(AsyncExtAndroid.kt:6)
		at com.soywiz.korio.KorioAndroidKt.Korio(KorioAndroid.kt:8)
		at com.soywiz.korgw.KorgwActivity.onCreate(KorgwActivity.kt:166)
		at android.app.Activity.performCreate(Activity.java:7159)
		at android.app.Activity.performCreate(Activity.java:7150)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
		at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
		at android.os.Handler.dispatchMessage(Handler.java:106)
		at android.os.Looper.loop(Looper.java:205)
		at android.app.ActivityThread.main(ActivityThread.java:6991)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by TobseF** [comment]
Another problem is that the **lenght** of a `NativeSound` returns 0s.
So my intention to delay for the lenght of the song doesn't work. 
``` kotlin
val nextSong: NativeSound = playList.random()
playing = nextSong.play()
val lenght = nextSong.length
delay(lenght )
```
But it the alternative `nextSong.playAndWait()` didn't worked on the JS Build.

🎧 I summarize a few audio related problems here. They belong all to one wish... I want to get background music working on Java, Android and the JS Build.

**Comment by soywiz** [comment]
`readAudioStream` doesn't work as you might think. It uses defined formats.
https://github.com/korlibs/korau/commit/9da2b7d4c963f606aa695bde4062d2e10e119c68#diff-66c7a3685b1205208b4d58d3883738d5R170

You will need to use `readNativeSound(streaming = true)` or the new `readNativeMusic()` (that will be included in the next version) that is an alias for `readNativeSound(streaming = true)`.

On JVM, stereo MP3 had issues (playback was too fast) and streaming was not being honored, but decoded the whole music in-memory. In next version those issues should have been fixed

**Comment by TobseF** [comment]
After the last update (Korge 1.10.2.1) the music play instantly (without calling `play()`):
``` kotlin
resourcesVfs["music.mp3"].readNativeMusic() // diretly starts the music
```
Is this intended?

I wan't to play the music files as Background music and change to the next song after the first ended.
Because the `NativeSound.lenght` retuns `null` on the JVM, I made workaround to also provide the play time with the file and make a `delay` after music start.

**Comment by soywiz** [comment]
I have done a pretty big revamp of the code. Hopefully will get it working on all targets before weekend (including looping, music streaming, proper getting of the length, panning, volume and pitch).

**Comment by soywiz** [comment]
With Korge 1.11.1.0 you can do this:
```kotlin
resourcesVfs["music.mp3"].readMusic().playForever()
```

**Comment by TobseF** [comment]
Great improvements in the sound sound API!
Now the `playAndWait()` also works on the JVM.

But my jukebox still cannot rock the stage. It stops after playing the first song:
``` kotlin
        while (true) {
            val nextSong: NativeSound = playList.random()
            nextSong.playAndWait()
        }
```
The `playList` contains the two mentioned music files. Both can be placed once.

**Comment by soywiz** [comment]
Tried this and can't reproduce:

```
	val music1 = resourcesVfs["sample.wav"].readMusic()
	val music2 = resourcesVfs["sample.mp3"].readMusic()
	val music3 = resourcesVfs["sample.mp3"].readMusic()
	while (true) {
		println("[1]")
		music1.playAndWait()
		delay(1.seconds)
		music2.playAndWait()
		delay(1.seconds)
		music3.playAndWait()
	}
``

**Comment by TobseF** [comment]
Thanks for the investigation. I found the problem. Does I need to do the `readMusic()` and the `playAndWait()` in the same coroutine context?
I used a `AsyncDependency` and loaded the music (`readMusic()`) there in the `init()`. I double checked that it's called before I play the music -otherwise my music would be null. But then the music doesn't play.
I fixed it by moving the `.readMusic()` into the `stage.launch { `where I also do my music loop. Moving the `.readMusic()` before the `stage.launch` will break it again.

**Broken**
``` kotlin
val music = resourcesVfs["music/monkey_drama.mp3"].readMusic()
stage.launch {
    while (true){
        delay(1.seconds)
        music.playAndWait()
    }
}
```

**Works**
``` kotlin
stage.launch {
    val music = resourcesVfs["music/monkey_drama.mp3"].readMusic()
    while (true){
        delay(1.seconds)
        music.playAndWait()
    }
}
```

**Comment by soywiz** [comment]
Maybe there is a Job that gets cancelled? In which function are you executing that? `suspend fun main() = Korge { ... }` or as part of a scene and if that's the case, in which function?

**Comment by TobseF** [comment]
Practical inside the `Korge { ... }`. You can check it here:  
[JukeBox.kt](https://github.com/TobseF/Candy-Crush-Clone/blob/MusicTest/src/commonMain/kotlin/j4k/candycrush/audio/JukeBox.kt)

**Comment by soywiz** [comment]
The first time it seems that you are executing it in the injector phase. Constructing/injecting conceptually shouldn't perform any actions.
Not sure if  there is a Job or something for the initialization, but maybe the initialization phase gets destroyed somehow or have a different lifecycle, not sure.

**Comment by TobseF** [comment]
I tried several variants. Inside `mapSingleton` or during `AsyncDependency.init()`. Nothing changed.
With the current
``` kotlin
 suspend operator fun invoke(injector: AsyncInjector): JukeBox {
            val jukeBox = JukeBox(injector.get()).load()
            injector.mapSingleton { jukeBox }
            return jukeBox
        }
```
The `load()` should be called synchron to the `invoke` call in from the `main`. The Inject just returns the loaded instance.

**Comment by soywiz** [comment]
I think this is the culprit: https://github.com/korlibs/korge/blob/a9dbb3d3382818e05123c418af608985ef2471f5/korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt#L507

**Comment by soywiz** [comment]
Can you try?

```
git clone https://github.com/korlibs/korge.git
cd korge
git checkout fix/try.to.fix.coroutine.scope.on.initialization
sed -i 's/^version=.*/version=1.11.1/g' gradle.properties 
./gradlew :korge:publishToMavenLocal
#./gradlew korge:publishJvmPublicationToMavenLocal
```

Then try again your old approach to see if it is fixed with this?

**Comment by TobseF** [comment]
I tried... fought with gradle, then with the IDE and ended up copying the changed `Korge` to my project 😖
The changed line isn't called... you might change line `467` with the ` views.launchImmediately{`. I also tired different variants here -also passed the `gameWindow.coroutineDispatcher`. But the music kept muted.

**Comment by TobseF** [comment]
After updating to Korge `1.11.1.0` the audio stopped working on the JS build.
In the Console it prints the warning:
> korau-root-korau.js:8121 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

But I think this already was there before the update.

**Comment by soywiz** [comment]
I have created a separate issue for the JS stuff, so I'm closing this one.
